services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api-example
    ports:
        - "3306:3306"
    volumes:
        - db-data-sql:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
        interval: 30s
        timeout: 10s
        retries: 5


  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PATH_DB: jdbc:mysql://localhost:3306/api-example?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SQL_USER: root
      SQL_PASSWORD: root
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      db:
        condition: service_healthy


volumes:
  db-data-sql: